// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: customer.proto

package server

import (
	"context"

	"gz-dango/apps/customer/rpc/internal/logic/menu"
	"gz-dango/apps/customer/rpc/internal/svc"
	"gz-dango/apps/customer/rpc/pb"
)

type MenuServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMenuServer
}

func NewMenuServer(svcCtx *svc.ServiceContext) *MenuServer {
	return &MenuServer{
		svcCtx: svcCtx,
	}
}

func (s *MenuServer) CreateMenu(ctx context.Context, in *pb.CreateMenuRequest) (*pb.MenuOut, error) {
	l := menulogic.NewCreateMenuLogic(ctx, s.svcCtx)
	return l.CreateMenu(in)
}

func (s *MenuServer) UpdateMenu(ctx context.Context, in *pb.UpdateMenuRequest) (*pb.MenuOut, error) {
	l := menulogic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

func (s *MenuServer) DeleteMenu(ctx context.Context, in *pb.DeleteMenuRequest) (*pb.NilOut, error) {
	l := menulogic.NewDeleteMenuLogic(ctx, s.svcCtx)
	return l.DeleteMenu(in)
}

func (s *MenuServer) GetMenu(ctx context.Context, in *pb.GetMenuRequest) (*pb.MenuOut, error) {
	l := menulogic.NewGetMenuLogic(ctx, s.svcCtx)
	return l.GetMenu(in)
}

func (s *MenuServer) ListMenu(ctx context.Context, in *pb.ListMenuRequest) (*pb.PagMenuOutBase, error) {
	l := menulogic.NewListMenuLogic(ctx, s.svcCtx)
	return l.ListMenu(in)
}
