// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: customer.proto

package role

import (
	"context"

	"gz-dango/apps/customer/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BoolValue               = pb.BoolValue
	ButtonOut               = pb.ButtonOut
	ButtonOutBase           = pb.ButtonOutBase
	ChangePasswordRequest   = pb.ChangePasswordRequest
	CreateButtonRequest     = pb.CreateButtonRequest
	CreateMenuRequest       = pb.CreateMenuRequest
	CreatePermissionRequest = pb.CreatePermissionRequest
	CreateRoleRequest       = pb.CreateRoleRequest
	CreateUserRequest       = pb.CreateUserRequest
	DeleteButtonRequest     = pb.DeleteButtonRequest
	DeleteMenuRequest       = pb.DeleteMenuRequest
	DeletePermissionRequest = pb.DeletePermissionRequest
	DeleteRoleRequest       = pb.DeleteRoleRequest
	DeleteUserRequest       = pb.DeleteUserRequest
	GetButtonRequest        = pb.GetButtonRequest
	GetMenuRequest          = pb.GetMenuRequest
	GetPermissionRequest    = pb.GetPermissionRequest
	GetRoleRequest          = pb.GetRoleRequest
	GetUserRequest          = pb.GetUserRequest
	ListButtonRequest       = pb.ListButtonRequest
	ListMenuRequest         = pb.ListMenuRequest
	ListPermissionRequest   = pb.ListPermissionRequest
	ListRoleRequest         = pb.ListRoleRequest
	ListUserRequest         = pb.ListUserRequest
	LoginOut                = pb.LoginOut
	LoginRequest            = pb.LoginRequest
	MenuOut                 = pb.MenuOut
	MenuOutBase             = pb.MenuOutBase
	MetaSchemas             = pb.MetaSchemas
	NilOut                  = pb.NilOut
	PagButtonOutBase        = pb.PagButtonOutBase
	PagMenuOutBase          = pb.PagMenuOutBase
	PagPermissionOutBase    = pb.PagPermissionOutBase
	PagRoleOutBase          = pb.PagRoleOutBase
	PagUserOut              = pb.PagUserOut
	PermissionOutBase       = pb.PermissionOutBase
	ResetPasswordRequest    = pb.ResetPasswordRequest
	RoleOut                 = pb.RoleOut
	RoleOutBase             = pb.RoleOutBase
	UInt32Value             = pb.UInt32Value
	UpdateButtonRequest     = pb.UpdateButtonRequest
	UpdateMenuRequest       = pb.UpdateMenuRequest
	UpdatePermissionRequest = pb.UpdatePermissionRequest
	UpdateRoleRequest       = pb.UpdateRoleRequest
	UpdateUserRequest       = pb.UpdateUserRequest
	UserOut                 = pb.UserOut

	Role interface {
		CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*RoleOut, error)
		UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*RoleOut, error)
		DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*NilOut, error)
		GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*RoleOut, error)
		ListRole(ctx context.Context, in *ListRoleRequest, opts ...grpc.CallOption) (*PagRoleOutBase, error)
	}

	defaultRole struct {
		cli zrpc.Client
	}
)

func NewRole(cli zrpc.Client) Role {
	return &defaultRole{
		cli: cli,
	}
}

func (m *defaultRole) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*RoleOut, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

func (m *defaultRole) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*RoleOut, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultRole) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*NilOut, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

func (m *defaultRole) GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*RoleOut, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

func (m *defaultRole) ListRole(ctx context.Context, in *ListRoleRequest, opts ...grpc.CallOption) (*PagRoleOutBase, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.ListRole(ctx, in, opts...)
}
