// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: customer.proto

package menu

import (
	"context"

	"go-dango/apps/customer/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BoolValue               = pb.BoolValue
	ButtonOut               = pb.ButtonOut
	ButtonOutBase           = pb.ButtonOutBase
	ChangePasswordRequest   = pb.ChangePasswordRequest
	CreateButtonRequest     = pb.CreateButtonRequest
	CreateMenuRequest       = pb.CreateMenuRequest
	CreatePermissionRequest = pb.CreatePermissionRequest
	CreateRoleRequest       = pb.CreateRoleRequest
	CreateUserRequest       = pb.CreateUserRequest
	DeleteButtonRequest     = pb.DeleteButtonRequest
	DeleteMenuRequest       = pb.DeleteMenuRequest
	DeletePermissionRequest = pb.DeletePermissionRequest
	DeleteRoleRequest       = pb.DeleteRoleRequest
	DeleteUserRequest       = pb.DeleteUserRequest
	GetButtonRequest        = pb.GetButtonRequest
	GetMenuRequest          = pb.GetMenuRequest
	GetPermissionRequest    = pb.GetPermissionRequest
	GetRoleRequest          = pb.GetRoleRequest
	GetUserRequest          = pb.GetUserRequest
	ListButtonRequest       = pb.ListButtonRequest
	ListMenuRequest         = pb.ListMenuRequest
	ListPermissionRequest   = pb.ListPermissionRequest
	ListRoleRequest         = pb.ListRoleRequest
	ListUserRequest         = pb.ListUserRequest
	LoginOut                = pb.LoginOut
	LoginRequest            = pb.LoginRequest
	MenuOut                 = pb.MenuOut
	MenuOutBase             = pb.MenuOutBase
	MetaSchemas             = pb.MetaSchemas
	NilOut                  = pb.NilOut
	PagButtonOutBase        = pb.PagButtonOutBase
	PagMenuOutBase          = pb.PagMenuOutBase
	PagPermissionOutBase    = pb.PagPermissionOutBase
	PagRoleOutBase          = pb.PagRoleOutBase
	PagUserOut              = pb.PagUserOut
	PermissionOutBase       = pb.PermissionOutBase
	ResetPasswordRequest    = pb.ResetPasswordRequest
	RoleOut                 = pb.RoleOut
	RoleOutBase             = pb.RoleOutBase
	UInt32Value             = pb.UInt32Value
	UpdateButtonRequest     = pb.UpdateButtonRequest
	UpdateMenuRequest       = pb.UpdateMenuRequest
	UpdatePermissionRequest = pb.UpdatePermissionRequest
	UpdateRoleRequest       = pb.UpdateRoleRequest
	UpdateUserRequest       = pb.UpdateUserRequest
	UserOut                 = pb.UserOut

	Menu interface {
		CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*MenuOut, error)
		UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*MenuOut, error)
		DeleteMenu(ctx context.Context, in *DeleteMenuRequest, opts ...grpc.CallOption) (*NilOut, error)
		GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*MenuOut, error)
		ListMenu(ctx context.Context, in *ListMenuRequest, opts ...grpc.CallOption) (*PagMenuOutBase, error)
	}

	defaultMenu struct {
		cli zrpc.Client
	}
)

func NewMenu(cli zrpc.Client) Menu {
	return &defaultMenu{
		cli: cli,
	}
}

func (m *defaultMenu) CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*MenuOut, error) {
	client := pb.NewMenuClient(m.cli.Conn())
	return client.CreateMenu(ctx, in, opts...)
}

func (m *defaultMenu) UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*MenuOut, error) {
	client := pb.NewMenuClient(m.cli.Conn())
	return client.UpdateMenu(ctx, in, opts...)
}

func (m *defaultMenu) DeleteMenu(ctx context.Context, in *DeleteMenuRequest, opts ...grpc.CallOption) (*NilOut, error) {
	client := pb.NewMenuClient(m.cli.Conn())
	return client.DeleteMenu(ctx, in, opts...)
}

func (m *defaultMenu) GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*MenuOut, error) {
	client := pb.NewMenuClient(m.cli.Conn())
	return client.GetMenu(ctx, in, opts...)
}

func (m *defaultMenu) ListMenu(ctx context.Context, in *ListMenuRequest, opts ...grpc.CallOption) (*PagMenuOutBase, error) {
	client := pb.NewMenuClient(m.cli.Conn())
	return client.ListMenu(ctx, in, opts...)
}
