// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: customer.proto

package button

import (
	"context"

	"go-dango/apps/customer/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BoolValue               = pb.BoolValue
	ButtonOut               = pb.ButtonOut
	ButtonOutBase           = pb.ButtonOutBase
	ChangePasswordRequest   = pb.ChangePasswordRequest
	CreateButtonRequest     = pb.CreateButtonRequest
	CreateMenuRequest       = pb.CreateMenuRequest
	CreatePermissionRequest = pb.CreatePermissionRequest
	CreateRoleRequest       = pb.CreateRoleRequest
	CreateUserRequest       = pb.CreateUserRequest
	DeleteButtonRequest     = pb.DeleteButtonRequest
	DeleteMenuRequest       = pb.DeleteMenuRequest
	DeletePermissionRequest = pb.DeletePermissionRequest
	DeleteRoleRequest       = pb.DeleteRoleRequest
	DeleteUserRequest       = pb.DeleteUserRequest
	GetButtonRequest        = pb.GetButtonRequest
	GetMenuRequest          = pb.GetMenuRequest
	GetPermissionRequest    = pb.GetPermissionRequest
	GetRoleRequest          = pb.GetRoleRequest
	GetUserRequest          = pb.GetUserRequest
	ListButtonRequest       = pb.ListButtonRequest
	ListMenuRequest         = pb.ListMenuRequest
	ListPermissionRequest   = pb.ListPermissionRequest
	ListRoleRequest         = pb.ListRoleRequest
	ListUserRequest         = pb.ListUserRequest
	LoginOut                = pb.LoginOut
	LoginRequest            = pb.LoginRequest
	MenuOut                 = pb.MenuOut
	MenuOutBase             = pb.MenuOutBase
	MetaSchemas             = pb.MetaSchemas
	NilOut                  = pb.NilOut
	PagButtonOutBase        = pb.PagButtonOutBase
	PagMenuOutBase          = pb.PagMenuOutBase
	PagPermissionOutBase    = pb.PagPermissionOutBase
	PagRoleOutBase          = pb.PagRoleOutBase
	PagUserOut              = pb.PagUserOut
	PermissionOutBase       = pb.PermissionOutBase
	ResetPasswordRequest    = pb.ResetPasswordRequest
	RoleOut                 = pb.RoleOut
	RoleOutBase             = pb.RoleOutBase
	UInt32Value             = pb.UInt32Value
	UpdateButtonRequest     = pb.UpdateButtonRequest
	UpdateMenuRequest       = pb.UpdateMenuRequest
	UpdatePermissionRequest = pb.UpdatePermissionRequest
	UpdateRoleRequest       = pb.UpdateRoleRequest
	UpdateUserRequest       = pb.UpdateUserRequest
	UserOut                 = pb.UserOut

	Button interface {
		CreateButton(ctx context.Context, in *CreateButtonRequest, opts ...grpc.CallOption) (*ButtonOut, error)
		UpdateButton(ctx context.Context, in *UpdateButtonRequest, opts ...grpc.CallOption) (*ButtonOut, error)
		DeleteButton(ctx context.Context, in *DeleteButtonRequest, opts ...grpc.CallOption) (*NilOut, error)
		GetButton(ctx context.Context, in *GetButtonRequest, opts ...grpc.CallOption) (*ButtonOut, error)
		ListButton(ctx context.Context, in *ListButtonRequest, opts ...grpc.CallOption) (*PagButtonOutBase, error)
	}

	defaultButton struct {
		cli zrpc.Client
	}
)

func NewButton(cli zrpc.Client) Button {
	return &defaultButton{
		cli: cli,
	}
}

func (m *defaultButton) CreateButton(ctx context.Context, in *CreateButtonRequest, opts ...grpc.CallOption) (*ButtonOut, error) {
	client := pb.NewButtonClient(m.cli.Conn())
	return client.CreateButton(ctx, in, opts...)
}

func (m *defaultButton) UpdateButton(ctx context.Context, in *UpdateButtonRequest, opts ...grpc.CallOption) (*ButtonOut, error) {
	client := pb.NewButtonClient(m.cli.Conn())
	return client.UpdateButton(ctx, in, opts...)
}

func (m *defaultButton) DeleteButton(ctx context.Context, in *DeleteButtonRequest, opts ...grpc.CallOption) (*NilOut, error) {
	client := pb.NewButtonClient(m.cli.Conn())
	return client.DeleteButton(ctx, in, opts...)
}

func (m *defaultButton) GetButton(ctx context.Context, in *GetButtonRequest, opts ...grpc.CallOption) (*ButtonOut, error) {
	client := pb.NewButtonClient(m.cli.Conn())
	return client.GetButton(ctx, in, opts...)
}

func (m *defaultButton) ListButton(ctx context.Context, in *ListButtonRequest, opts ...grpc.CallOption) (*PagButtonOutBase, error) {
	client := pb.NewButtonClient(m.cli.Conn())
	return client.ListButton(ctx, in, opts...)
}
